name: Variable-env and secret level

on:
  push:
    paths:
      - 'src/**'
      - 'my_test.txt'

env:
  MESSAGE: "Hello DevOps"
  ENV_NAME: "Production"

jobs:
  branch:
    name: Testing Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Variables
        env:
          My_Name: "Aorko"
        run: |
          echo "Hello, My Name is $My_Name"
          echo "Message is $MESSAGE"
          echo "Environment is $ENV_NAME"
