name: Secure Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@<FULL_COMMIT_SHA>

      - name: Print Message
        run: echo "Pinned version used"

